name: publish to GitHub Packages

on:
  release:
    types: [created]

jobs:
#  build:
#    name: build and test
#    runs-on: ubuntu-latest
#    steps:
#      - name: checkout code
#        uses: actions/checkout@v4
#      - name: setup node
#        uses: actions/setup-node@v3
#        with:
#          node-version: 18.17.1
#      - name: build with devdependencies
#        run: yarn
#      - name: test
#        run: yarn test

  publish-gpr:
#    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
      - name: install prod dependencies
        run: yarn
      - name: build
        run: yarn build
      - name: login to github packages
        run: "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" >> ~/.npmrc
      - name: publish
        run: yarn publish --access public --registry https://npm.pkg.github.com
